name: Update Frontmatter on Push

on:
  push:
    paths:
      - "**/*.md"
    branches:
      - master

jobs:
  update-frontmatter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install python-frontmatter

      - name: Run Bash script to get new and modified files
        run: |
          chmod +x scripts/get_files.sh
          ./scripts/get_files.sh

      - name: Add "publish" frontmatter to new files and update "lastUpdate" for modified files
        run: |
          python scripts/update_frontmatter.py

      - name: Commit and push frontmatter changes
        run: |
          git config user.name "filip-melka"
          git config user.email "melka.filip@proton.me"
          git add *.md
          git commit -m "Update frontmatter on push" || echo "No changes to commit"
          git push
